### ISSUE TITLE
A teacher can create a course with several sections

### ISSUE THREAD

**Issue by sylvain-reynaud** [polyflix/frontend#112]
A teacher can create a course with several (empty) sections, name the sections and save it (keep the top of the current page).

Integrate this solution above :
![Image](https://user-images.githubusercontent.com/20583601/213177070-320228b2-1a41-46ed-a8bc-167c1f4483fe.png)

## todos:

- [ ] create a course with a (empty) section
- [ ] an empty section is already waiting for the user when opening the page (no need to click on add section for the 1st section)
- [ ] a section is nameable
- [ ] create a course with several (empty) sections
